// episodes/137/waypoint-examples/docker/reactjs/src/App.js
import React from 'react';
import logo from './logo.svg';
import language from './language.svg';
import hashi from './hashi.svg';
import './App.css';

function App() {
  return ( 
    <div class="container">
      <header>
        <a href="https://waypointproject.io" class="logo">
          <img src={logo} />
        </a>
      </header>
      <section class="content">
        <div class="language-icon">
          <img src={language} />
        </div>
        <h1>This React app was deployed with Waypoint.</h1>
        <p>
          Try making a change to this text locally and run <code>waypoint up</code> again to see it.
        </p>
        <p>
          Read the <a href="https://waypointproject.io/docs">documentation</a> for more about Waypoint.
        </p>
      </section>
      <footer>
        <a href="https://hashicorp.com" class="hashi">
          <img src={hashi} />
        </a>
      </footer>
    </div>
  );
}

export default App;

// episodes/137/waypoint-examples/docker/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'angulardemo';
}

<!DOCTYPE html>
<html>
  <head>
    <title>Waypoint Node.js Example</title>
  </head>

  <body>
    <div class="container">
      <header>
        <a href="https://waypointproject.io" class="logo">
          <img src="/assets/logo.svg" alt="Logo" />
        </a>
      </header>
      <section class="content">
        <div class="language-icon">
          <img class="logo" src="/assets/language.svg" alt="Angular Icon" />
        </div>
        <h1>This Angular app was deployed with Waypoint.</h1>
        <p>
          Try making a change to this text locally and run
          <code>waypoint up</code> again to see it.
        </p>
        <p>
          Read the
          <a href="https://waypointproject.io/docs">documentation</a> for more
          about Waypoint.
        </p>
      </section>
      <footer>
        <a href="https://hashicorp.com" class="hashi">
          <img src="/assets/hashi.svg" alt="HashiCorp" />
        </a>
      </footer>
    </div>
  </body>
</html>
